version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=inkvi_images_store
      - JWT_SECRET=904328943fbu4fejrbnuvoieruvghoierwuiohvoeroveyhrvoeirvhoerivhrvbrr
    depends_on:
      - db

  db:
    image: mysql:8
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: inkvi_images_store
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
